### ISSUE TITLE
Singleton Datingnode service for DI

### ISSUE THREAD

**Issue by jimmyff** [jimmyff/datingnode-app-angular#1]
Not quite sure the correct way to have a single instance of the Datingnode service available for DI. I believe my current implementation is re-loading it for every component that needs it.

**Comment by zoechi** [comment]
Provide it only at `AppComponent` or `bootstrap(AppComponent, [...])`, then there will only be only a single instance for the whole application.

**Comment by zoechi** [comment]
I think this is done
