### ISSUE TITLE
Query with nested model object isn't executing

### ISSUE THREAD

**Issue by jimmyff** [jimmyff/datingnode-app-angular#4]
https://github.com/jimmyff/datingnode-app-angular/blob/master/lib/components/screens/log_in/log_in.component.dart#L38

This authentication query isn't being sent. This was the same before using built_value but this was as we hadn't implemented nested objects on that version.

**Comment by jimmyff** [comment]
the test in datingnode.dart shows the following error message:

 Converting object to an encodable object failed.
  dart:convert                                  JsonCodec.encode
  package:datingnode/src/dispatcher.dart 48:14  Dispatcher.send.<async>

**Comment by zoechi** [comment]
I think this is fixed.
